FROM --platform=$BUILDPLATFORM golang:1.25.5-alpine AS builder

RUN apk add --no-cache -U git curl
RUN sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

WORKDIR /go/src/medialize
COPY . /go/src/medialize/

RUN --mount=type=cache,target=/go/pkg \
    go mod download -x

ARG TARGETOS
ARG TARGETARCH

RUN --mount=type=cache,target=/go/pkg \
    --mount=type=cache,target=/root/.cache/go-build \
    task generate build GOOS=${TARGETOS} GOARCH=${TARGETARCH}

FROM alpine:3.23@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659

RUN apk add --no-cache ca-certificates mailcap

ENTRYPOINT ["/usr/bin/medialize"]
CMD ["help"]

COPY --from=builder /go/src/medialize/bin/medialize /usr/bin/medialize
WORKDIR /
