FROM amd64/alpine:3.18@sha256:d695c3de6fcd8cfe3a6222b0358425d40adfd129a8a47c3416faff1a8aece389

ENTRYPOINT ["/usr/bin/medialize"]
CMD ["help"]

RUN apk add --no-cache ca-certificates mailcap imagemagick && \
    rm -rf /var/cache/apk/*

COPY bin/medialize /usr/bin/medialize
