FROM arm32v6/alpine:3.21@sha256:9eb920e2ac62ae9ded9d084180d2f112823f8d4bcece2d13c5afdec326454100

ENTRYPOINT ["/usr/bin/medialize"]
CMD ["help"]

RUN apk add --no-cache ca-certificates mailcap imagemagick && \
    rm -rf /var/cache/apk/*

COPY bin/medialize /usr/bin/medialize
