FROM arm64v8/alpine:3.21@sha256:027789c1e8530f46d8211da2debc3f927eab8387ee2bb3922e466005d53cb0fe

ENTRYPOINT ["/usr/bin/medialize"]
CMD ["help"]

RUN apk add --no-cache ca-certificates mailcap imagemagick && \
    rm -rf /var/cache/apk/*

COPY bin/medialize /usr/bin/medialize
