FROM i386/alpine:3.17@sha256:3f57972158a12207fe5a2332005e6baf7bd73873e78b3f3a846df4fc93c3b7e6

ENTRYPOINT ["/usr/bin/medialize"]
CMD ["help"]

RUN apk add --no-cache ca-certificates mailcap imagemagick && \
    rm -rf /var/cache/apk/*

COPY bin/medialize /usr/bin/medialize
