FROM arm32v6/alpine:3.17@sha256:888fd5bcc23ddd20ac7248182033eb0db7073dd4ca92556f68d3c91b4de309d4

ENTRYPOINT ["/usr/bin/medialize"]
CMD ["help"]

RUN apk add --no-cache ca-certificates mailcap imagemagick && \
    rm -rf /var/cache/apk/*

COPY bin/medialize /usr/bin/medialize
